[package]
name = "endless_stream"
version = "0.1.0"
edition = "2021"
authors = ["uzerai <edvbot@gmail.com>"]
keywords = ["gamedev", "2d", "indie"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy =  { version = "0.9.1" }
